### ISSUE TITLE
incorrect console.log in an example

### ISSUE THREAD

**Issue by da-vaibhav** [WebReflection/js-glossary-on-demand#1]
In chapter **Object.defineProperty(obj, name, descriptor) → obj**, on page number 41, the second example outputs the console.log incorrectly as 64
`console.log(fixedSquare.size); // 64`
this should log 8, not 64.

**Comment by da-vaibhav** [comment]
on the same page the line says 

> And how can we create a square that cannot ever change its size?

although the `writable` property by [default is `false`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), the example only includes `enumerable` and `value` only. Hence is should also have `writable: false`

**Comment by WebReflection** [comment]
The example wasn't exactly wrong, the idea was to simulate `{size: 8}` hence the `enumerable` flag but you are right, it could have been definitively cleaner.

I don't think this second change deserves a release but the latest published version has, hopefully, fixed this.

Thanks for the report. Please file more if you think it's appropriate.

**Comment by da-vaibhav** [comment]
Thanks. another thing is `size` word in the line above quoted should be styled differently. (in book)
Because, although we are talking about the 'size' property of the object one may think about actually adding or removing property from obj.

>  cannot ever change its size?

 Hence, I think `size`, `length` are inappropriate properties of object even for the example purpose when it comes to modifying them.

**Comment by WebReflection** [comment]
> I think `size`, `length` are inappropriate properties ...

that's something the book does **not** want to do: use any sort of dogma for anything.

Whatever it works to explain the concept is fine. In this case it's not worth to introduce a "_dogma_" about a property name considering the main book target.

They will eventually figure out how to write nice APIs and decide worth property names digging more as they need.

Talking about what's a good name for a property or not is surely out of `Object.defineProperty` scope.

I hope you understand what I am saying, and I'm changing already that `size` to be shown as code.

Thanks.
